### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by bob102o** [michaelshumshum/kahoot-annoyer#7]
I get the error _Traceback (most recent call last):
  File "C:\Users\lazar\Downloads\kahoot-annoyer-main\kahoot-annoyer-main\flood.py", line 129, in <module>
    from _ui import *
  File "C:\Users\lazar\Downloads\kahoot-annoyer-main\kahoot-annoyer-main\_ui.py", line 1, in <module>
    import npyscreen
  File "C:\Users\lazar\AppData\Local\Programs\Python\Python39\lib\site-packages\npyscreen\__init__.py", line 5, in <module>
    from .wgwidget                  import TEST_SETTINGS, ExhaustedTestInput, add_test_input_from_iterable, add_test_input_ch
  File "C:\Users\lazar\AppData\Local\Programs\Python\Python39\lib\site-packages\npyscreen\wgwidget.py", line 5, in <module>
    import curses
  File "C:\Users\lazar\AppData\Local\Programs\Python\Python39\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'_

**Comment by michaelshumshum** [comment]
if you are on windows, `pip install windows-curses` 

curses doesnt work on windows yet, so maybe try the port. if it doesnt work, just dont use the ui.

**Comment by michaelshumshum** [comment]
closed because this is a known issue with no solution at the moment. we just have to wait for a proper npyscreen workaround for windows.
